apiVersion: skaffold/v2beta4
kind: Config
build:
  tagPolicy:
    gitCommit: {}
  artifacts:
  - image: jvm-operator
    context: .
  local: {}
deploy:
  kubectl:
    manifests:
    - authorization.yml
    - deploy.yml